### ISSUE TITLE
 Error while setting up awb platform for sensor 

### ISSUE THREAD

**Issue by t0kn4r** [jensweimann/awb#6]
Hi jens.

Würde mich gern an deinem Sensor bedienen. Leider kommt immer folgender Fehler nachdem ich den Sensor definiert habe:
```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/awb/sensor.py", line 58, in setup_platform
    add_devices([AwbSensor(config.get(CONF_NAME), config.get(CONF_STREET_CODE), config.get(CONF_STREET_NUMBER), config.get(CONF_DAY), value_template)])
  File "/config/custom_components/awb/sensor.py", line 73, in __init__
    self.update()
  File "/config/custom_components/awb/sensor.py", line 116, in update
    trashdates = value_json['trashdates']['trashdate']
TypeError: list indices must be integers or slices, not str

```
Muss ich noch weitere Programme installieren? Danke im voraus. ;)

t0kn4r

**Comment by jensweimann** [comment]
Hallo t0kn4r,

evtl sind die Angaben für Straße und Hausnummer falsch? Ich bin zurzeit leider zeitlich etwas ausgelastet, sonst könntest du noch dieses Projekt probieren: https://github.com/mampfes/hacs_waste_collection_schedule

**Comment by t0kn4r** [comment]
hmm irgendwie funktionieren die 4 stelligen Straßen Codes nicht.. 3 stellig zB aus Mülheim oder dein Code funktionieren.. 
danke trotzdem :)

**Comment by jensweimann** [comment]
Das ist dann ein Schnittstellenproblem würde ich mal platt annehmen.
